CREATE TABLE `group_codes` (
	`code` varchar(10) NOT NULL,
	`createdBy` varchar(36),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`memberCount` int DEFAULT 1,
	CONSTRAINT `group_codes_code` PRIMARY KEY(`code`)
);
--> statement-breakpoint
CREATE TABLE `sports_day_registrations` (
	`id` varchar(36) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`fullName` varchar(255) NOT NULL,
	`email` varchar(255) NOT NULL,
	`instagramHandle` varchar(100),
	`attendedBefore` boolean,
	`comingType` enum('solo','with_friends'),
	`groupCode` varchar(10),
	`groupRole` enum('creator','joiner'),
	`date4July` boolean DEFAULT false,
	`date11July` boolean DEFAULT false,
	`date18July` boolean DEFAULT false,
	`dateAny` boolean DEFAULT false,
	`competitiveness` enum('vibes','balanced','winner'),
	`teammateType` enum('motivator','strategist','wildcard','silent_assassin','energy_bringer'),
	`strongestEvent` enum('speed','strength','endurance','coordination','vibes'),
	`fear` enum('sprinting','team_events','letting_team_down','looking_unfit','nothing'),
	`eventMotivation` text,
	`captainVoteInterest` enum('yes','no','maybe'),
	`sportsDayProfile` varchar(50),
	`profileTagline` text,
	`shirtSize` enum('XS','S','M','L','XL','XXL'),
	`shirtFit` enum('regular','oversized'),
	`healthNotes` text,
	`contentConsent` enum('yes','no','ask'),
	`team` enum('red','blue','pink','orange'),
	`revealStatus` enum('locked','unlocked') DEFAULT 'locked',
	`accessType` enum('free','priority') DEFAULT 'free',
	`paymentStatus` enum('unpaid','paid') DEFAULT 'unpaid',
	`shopifyOrderId` varchar(100),
	`paidAt` timestamp,
	`referralCode` varchar(10),
	`referredBy` varchar(10),
	`referralCount` int DEFAULT 0,
	`referralRewardUnlocked` boolean DEFAULT false,
	`klaviyoTags` json,
	`shopifyCustomerId` varchar(100),
	`ipAddress` varchar(45),
	`userAgent` text,
	CONSTRAINT `sports_day_registrations_id` PRIMARY KEY(`id`),
	CONSTRAINT `sports_day_registrations_email_unique` UNIQUE(`email`),
	CONSTRAINT `sports_day_registrations_referralCode_unique` UNIQUE(`referralCode`)
);
